#!/bin/bash

TARGET="/usr/local/include/pretty-logger/"
SRCS="src/logger.cpp src/Logger.h"

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this as root."
    exit 1
fi

echo "Copying $SRCS to $TARGET"

mkdir -p $TARGET &&
cp $SRCS $TARGET
